services:
    influxdb:
        container_name: influxdb
        image: influxdb:latest
        restart: unless-stopped
        volumes:
          - ./:/etc/influxdb2/config.yml
          - ./data:/var/lib/influxdb2
        ports:
          - "8086:8086"