version: '3.8'
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bernitech
      - MONGO_INITDB_ROOT_PASSWORD=bernitech
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
